post http://localhost:3001/api/tasks
Content-Type: application/json

{
  "name": "Another task for the user",
  "dur": 4,
  "note": "Just a note for the user's other task",
  "blocksCompleted": 0,
  "userId": "623f83e9bf5d3cfa230db243"
}